repos:
    - repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
          - id: black
    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort
            args: ["--profile", "black"]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: detect-private-key
          - id: check-added-large-files
          - id: mixed-line-ending
    - repo: https://github.com/asottile/blacken-docs
      rev: v1.12.1
      hooks:
        - id: blacken-docs
    - repo: https://github.com/myint/autoflake
      rev: v1.4
      hooks:
        - id: autoflake
          args: [ '--in-place','--recursive', '--expand-star-imports', '--remove-unused-variables']
    -   repo: https://github.com/pycqa/pylint
        rev: v2.14.5
        hooks:
        -   id: pylint
            name: pylint
            entry: pylint
            language: python
            types: [python]